api_platform:
    title: Poc in memory repositories
    version: 1.0.0
    show_webby: false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths: [
            '%kernel.project_dir%/src/Api/Resources'
        ]
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
