services:
  php:
    build:
      context: ./docker/php
    container_name: poc_in_memory_repositories_php
    volumes:
      - ./:/var/www/html
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=poc_in_memory_repositories_db
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  db:
    image: postgres:17
    container_name: poc_in_memory_repositories_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poc_in_memory_repositories_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
